-- Amazon RDS
GRANT CREATE SESSION, SELECT ANY TRANSACTION, SELECT ANY DICTIONARY TO C##BLOGWEBSITE;
GRANT SELECT ON SYSTEM.LOGMNR_COL$ TO C##BLOGWEBSITE;
GRANT SELECT ON SYSTEM.LOGMNR_OBJ$ TO C##BLOGWEBSITE;
GRANT SELECT ON SYSTEM.LOGMNR_USER$ TO C##BLOGWEBSITE;
GRANT SELECT ON SYSTEM.LOGMNR_UID$ TO C##BLOGWEBSITE;
ALTER USER C##BLOGWEBSITE QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO C##BLOGWEBSITE;
GRANT CREATE TABLE TO C##BLOGWEBSITE;
GRANT CREATE SEQUENCE TO C##BLOGWEBSITE;
GRANT CREATE TRIGGER TO C##BLOGWEBSITE;
GRANT LOGMINING TO C##BLOGWEBSITE;

--/
begin
  rdsadmin.rdsadmin_util.grant_sys_object('DBMS_LOGMNR', 'C##BLOGWEBSITE', 'EXECUTE');
end;
/


--/
begin
  rdsadmin.rdsadmin_util.alter_supplemental_logging('ADD');
  rdsadmin.rdsadmin_util.alter_supplemental_logging('ADD','ALL');
end;
/




--ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

GRANT FLASHBACK ANY TABLE TO myuser;


